.POSIX:

# This Makefile was generated by maje
# See https://gitlab.com/jkaivo/maje/ for more information
# Do not edit this Makefile by hand

CC=c99
LD=$(CC)
CFLAGS=-Wall -Wextra -Wpedantic -Werror -g
LDFLAGS=
LDLIBS=
SRCDIR=.
OBJDIR=.
BINDIR=$(OBJDIR)

all: $(BINDIR)/deonebook

clean:
	rm -f $(BINDIR)/deonebook $(OBJDIR)/*.o

$(BINDIR)/deonebook: $(OBJDIR)/deonebook.o
$(OBJDIR)/deonebook.o: $(SRCDIR)/deonebook.c
	$(CC) $(CFLAGS) -o $@ -c $(SRCDIR)/deonebook.c

$(BINDIR)/deonebook:
	$(LD) $(LDFLAGS) -o $@ $(OBJDIR)/*.o $(LDLIBS)
